<a href="https://colab.research.google.com/github/Maks3174/Phy/blob/main/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [1]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [2]:
even_numbers = np.arange(30, 71, 2)
print(even_numbers)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [3]:
random_numbers = np.linspace(0, 1, 11, endpoint=False)[1:]
print(random_numbers)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [4]:
def add_border(matrix):
    n = matrix.shape[0]
    new_matrix = np.zeros((n + 2, n + 2))
    new_matrix[1:-1, 1:-1] = matrix
    return new_matrix

matrix = np.array([[1, 2], [3, 4]])
new_matrix = add_border(matrix)
print(new_matrix)


[[0. 0. 0. 0.]
 [0. 1. 2. 0.]
 [0. 3. 4. 0.]
 [0. 0. 0. 0.]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [5]:
before_dtype = new_matrix.dtype
print(f"Тип даних до зміни: {before_dtype}")

new_matrix = new_matrix.astype(int)

after_dtype = new_matrix.dtype
print(f"Тип даних після зміни: {after_dtype}")


Тип даних до зміни: float64
Тип даних після зміни: int64


#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [8]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

x = np.where(x == var, -1, np.where(x > var, -1, np.where(x < var, -1, x)))
print(x)

[-1 -1 -1 -1 -1 -1 -1 -1]


#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [9]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

X[np.isnan(X)] = -1

print(X)

[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [10]:
matrix = np.random.rand(4, 6)
print("Початкова матриця 4x6:")
print(matrix)

# Зміна розміру матриці на 3x8
reshaped_matrix = np.resize(matrix, (3, 8))
print("\nМатриця після зміни розміру на 3x8:")
print(reshaped_matrix)

Початкова матриця 4x6:
[[0.35457697 0.95775553 0.12445895 0.41956055 0.02742238 0.47778037]
 [0.19337472 0.87885567 0.52531947 0.49252172 0.5337568  0.2374712 ]
 [0.34409454 0.46487784 0.26098067 0.57032548 0.45284917 0.91608793]
 [0.21664915 0.0230001  0.58583759 0.79660666 0.39488684 0.93263186]]

Матриця після зміни розміру на 3x8:
[[0.35457697 0.95775553 0.12445895 0.41956055 0.02742238 0.47778037
  0.19337472 0.87885567]
 [0.52531947 0.49252172 0.5337568  0.2374712  0.34409454 0.46487784
  0.26098067 0.57032548]
 [0.45284917 0.91608793 0.21664915 0.0230001  0.58583759 0.79660666
  0.39488684 0.93263186]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [12]:
matrix = np.ones((3, 4))
print("Матриця 3x4 з одиниць:")
print(matrix)

mean_values = np.mean(matrix, axis=0)
print("\nСереднє арифметичне кожного стовпчика:")
print(mean_values)

Матриця 3x4 з одиниць:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Середнє арифметичне кожного стовпчика:
[1. 1. 1. 1.]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [13]:
random_matrix = np.random.rand(5, 6) * 100

rounded_matrix = np.round(random_matrix, 1)

sorted_column_indices = np.argsort(rounded_matrix[0])

sorted_matrix = rounded_matrix[:, sorted_column_indices]

print("Випадкова матриця:\n", rounded_matrix)
print("\nМатриця з відсортованими стовпчиками:\n", sorted_matrix)


Випадкова матриця:
 [[52.8 72.6 34.7  4.4 40.2 15.8]
 [57.9 63.4 50.8 76.8 23.8  5.4]
 [37.5 10.1 20.1  6.1 35.9 13.3]
 [69.3 98.6 74.6  6.3 59.1  2.5]
 [94.9 78.1 91.  30.6 45.5 63.3]]

Матриця з відсортованими стовпчиками:
 [[ 4.4 15.8 34.7 40.2 52.8 72.6]
 [76.8  5.4 50.8 23.8 57.9 63.4]
 [ 6.1 13.3 20.1 35.9 37.5 10.1]
 [ 6.3  2.5 74.6 59.1 69.3 98.6]
 [30.6 63.3 91.  45.5 94.9 78.1]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [15]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])

result = X[np.logical_and(X >= 3, X <= 6)]

print("Елементи зі значенням між 3 і 6:", result)

Елементи зі значенням між 3 і 6: [3 4 5 6 6 5 4 3]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом цього стовпчика.

Після цього всі значення мають бути в межах [0, 1]

In [16]:
random_matrix = np.random.rand(5, 6) * 100

min_values = np.min(random_matrix, axis=0)
max_values = np.max(random_matrix, axis=0)

diff = max_values - min_values

normalized_matrix = (random_matrix - min_values) / diff

print("Випадкова матриця:\n", random_matrix)
print("\nНормалізована матриця (значення в межах [0, 1]):\n", normalized_matrix)

Випадкова матриця:
 [[ 7.34047352 41.8453103  48.66806796 91.48310156 35.38054721 41.5695347 ]
 [96.62481635 23.35897006 59.29102895 84.08549223 30.81292375 69.96770691]
 [84.98197834 60.52119769 30.12006192 95.53936779 31.15635978 61.04071581]
 [32.26179248 38.56809152 13.78331828 81.62869939 37.6659085   1.38693469]
 [83.44804642 70.47334659 23.40226397 66.1435353  47.3290068  99.58131092]]

Нормалізована матриця (значення в межах [0, 1]):
 [[0.         0.39237153 0.76656789 0.8620122  0.2765561  0.40921488]
 [1.         0.         1.         0.61035716 0.         0.69841853]
 [0.86959821 0.7887662  0.35898847 1.         0.02079404 0.6075071 ]
 [0.27912306 0.32281275 0.         0.52678093 0.41492797 0.        ]
 [0.85241791 1.         0.21136958 0.         1.         1.        ]]
