<a href="https://colab.research.google.com/github/Maks3174/Phy/blob/main/%D0%9A%D0%BE%D0%BF%D1%96%D1%8F_%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%BD%D0%B8%D0%BA%D0%B0_%22%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_numpy_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [3]:
import numpy as np

# Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [4]:
array = np.arange(1, 13)
print("Масив:", array)
print("Розмір масиву:", array.size)
print("Тип масиву:", array.dtype)


Масив: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Розмір масиву: 12
Тип масиву: int64


# Завдання 2
Зробіть на основі попереднього масиву матрицю з 4 стовчиками. Змініть тип даних матриці на float32. Виведіть транспоновану матрицю.

In [5]:
matrix = array.reshape((3, 4))
matrix = matrix.astype(np.float32)
transposed_matrix = matrix.T

print("Матриця з 4 стовпчиками:\n", matrix)
print("Транспонована матриця:\n", transposed_matrix)


Матриця з 4 стовпчиками:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Транспонована матриця:
 [[ 1.  5.  9.]
 [ 2.  6. 10.]
 [ 3.  7. 11.]
 [ 4.  8. 12.]]


#Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [6]:
chess_board = np.zeros((8, 8), dtype=int)

chess_board[1::2, ::2] = 1
chess_board[::2, 1::2] = 1

print("Матриця 8х8 в шаховому порядку:\n", chess_board)


Матриця 8х8 в шаховому порядку:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [7]:
random_matrix = np.random.rand(4, 3)

sum_columns = random_matrix.sum(axis=0)
sum_rows = random_matrix.sum(axis=1)
sum_all = random_matrix.sum()

print("Випадкова матриця 4х3:\n", random_matrix)
print("Сума елементів в стовпчиках:", sum_columns)
print("Сума елементів в рядках:", sum_rows)
print("Сума всіх елементів матриці:", sum_all)


Випадкова матриця 4х3:
 [[0.51705256 0.00328222 0.77533626]
 [0.81441866 0.25312033 0.72088823]
 [0.13501267 0.81888375 0.66805865]
 [0.4087372  0.30370227 0.12065509]]
Сума елементів в стовпчиках: [1.87522108 1.37898857 2.28493823]
Сума елементів в рядках: [1.29567103 1.78842722 1.62195507 0.83309456]
Сума всіх елементів матриці: 5.539147875094147


# Завдання 5
У попередній матриці від кожного рядка відніміть максимальний елемент цього рядка

In [8]:
max_in_rows = random_matrix.max(axis=1).reshape(-1, 1)
normalized_matrix = random_matrix - max_in_rows

print("Матриця після віднімання максимального елемента кожного рядка:\n", normalized_matrix)


Матриця після віднімання максимального елемента кожного рядка:
 [[-0.2582837  -0.77205404  0.        ]
 [ 0.         -0.56129833 -0.09353043]
 [-0.68387108  0.         -0.15082509]
 [ 0.         -0.10503492 -0.2880821 ]]


# Завдання 6
Є дані про вагу контейнерів для перевезення на кораблі: дрібний - 5 т,  малий - 10 т, середній - 25 т, великий - 40 т. На кораблі розміщено 20 дрібних, 5 малих, 10 середніх та 4 великих контейнерів. Знайти масу вантажу.

In [9]:
weights = np.array([5, 10, 25, 40])
quantities = np.array([20, 5, 10, 4])

total_weight = np.sum(weights * quantities)
print("Загальна маса вантажу на кораблі:", total_weight, "т")


Загальна маса вантажу на кораблі: 560 т


# Завдання 7
Тепер у нас декілька кораблів. Напишіть код для обчислення вантажу на кожному кораблі.

In [10]:
ships_quantities = np.array([
    [20, 5, 10, 4],
    [15, 10, 5, 8],
    [25, 8, 12, 3]
])

ships_weights = ships_quantities @ weights

print("Маса вантажу на кожному кораблі:", ships_weights, "т")


Маса вантажу на кожному кораблі: [560 620 625] т
